name: Lint

on:
  pull_request:
    branches:
      - '*'

env:
  TARGET_BRANCH: ${{ github.base_ref }}

jobs:
  rubocop:
    name: RuboCop
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Lint changed files
        run: bin/rubocop-ci ${{ env.TARGET_BRANCH }}
