name: Sync From Dradis

on:
  workflow_dispatch:
  schedule:
    - cron: '18 4 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Clone/Copy Remote
      run: |-
        git clone https://github.com/dradis/dradis-ce.git
        rsync -a --exclude={'Dockerfile','.gitlab','.git','.gitignore'} dradis-ce/ ./dradis
        rm -rf dradis-ce

    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Sync dradis: ${timestamp}" || exit 0
        git push
